fix problem

diff --git a/zet/20230919172630/root-knowledge-base-repo-path b/zet/20230919172630/root-knowledge-base-repo-path
--- a/zet/20230919172630/root-knowledge-base-repo-path
+++ b/zet/20230919172630/root-knowledge-base-repo-path
@@ -9,12 +9,19 @@ rp="$1"
 going=1
 while [ $going -ne 0 ]; do
   rp=$(dirname "$rp")
-  if [[ "$rp" == "/" ]]; then
-    going=0
-  fi
   ls "$rp/.git" 2>/dev/null >/dev/null || ls "$rp/.obsidian" 2>/dev/null >/dev/null
   if [ $? -eq 0 ]; then # found it
     going=0
     echo "$rp"
+  fi
+  if [[ "$rp" == "/" ]]; then
+    going=0
+    echo "root path not found" > /dev/stderr
+    exit 1
+  fi
+  if [[ "$rp" == "." ]]; then
+    going=0
+    echo "root path not found" > /dev/stderr
+    exit 1
   fi
 done
